version: "3.8"
services:
  windows-vm1:
    container_name: windows-vm1
    image: dockurr/windows    
    devices:
      - /dev/kvm
    cap_add:
      - NET_ADMIN
    stop_grace_period: 2m
    networks:
      vm-macvlan:
        ipv4_address: 192.168.1.100
    volumes:
      - windows1-data:/storage
      - ./../shared/win2019-eval.iso:/storage/tmp/win2019-eval.iso:ro

  windows-vm2:
    container_name: windows-vm2
    image: dockurr/windows    
    devices:
      - /dev/kvm
    cap_add:
      - NET_ADMIN
    stop_grace_period: 2m
    networks:
      vm-macvlan:
        ipv4_address: 192.168.1.101
    volumes:
      - windows2-data:/storage

networks:
  vm-macvlan:
    external: true

volumes:
  windows1-data:
  windows2-data:
