apiVersion: 1


datasources:


- name: Loki-Audit

  type: loki

  access: proxy

  url: http://loki:3100

  jsonData:

    httpHeaderName1: X-Scope-OrgID

  secureJsonData:

    httpHeaderValue1: audit




- name: Mimir

  type: prometheus

  access: proxy

  url: http://mimir:9009/prometheus