{
 "title": "Ecommerce LGTM Observability",
 "panels": [
  {
   "title": "Cart Count",
   "type": "stat",
   "gridPos": { "x": 0, "y": 0, "w": 6, "h": 6 },
   "targets": [
    { "expr": "cart_count_total" }
   ]
  },
  {
   "title": "Checkout Count",
   "type": "stat",
   "gridPos": { "x": 6, "y": 0, "w": 6, "h": 6 },
   "targets": [
    { "expr": "checkout_count_total" }
   ]
  },
  {
   "title": "Cart Traffic Rate",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 6, "w": 12, "h": 8 },
   "targets": [
    { "expr": "rate(cart_count_total[1m])" }
   ]
  },
  {
   "title": "Application Logs",
   "type": "logs",
   "gridPos": { "x": 0, "y": 14, "w": 24, "h": 8 },
   "targets": [
    {
     "expr": "{service_name=\"ecommerce-app\"}"
    }
   ]
  },
  {
   "title": "Errors From Application",
   "type": "logs",
   "gridPos": { "x": 0, "y": 22, "w": 24, "h": 8 },
   "targets": [
    {
     "expr": "{service_name=\"ecommerce-app\"} |= \"error\""
    }
   ]
  }
 ]
}