
services:


 minio:

  image: minio/minio

  container_name: minio

  command: server /data --console-address ":9001"

  environment:

   MINIO_ROOT_USER: admin

   MINIO_ROOT_PASSWORD: password123

  ports:

  - "9000:9000"

  - "9001:9001"



 createbucket:

  image: minio/mc

  depends_on:

  - minio

  entrypoint: >

   /bin/sh -c "

   sleep 5;

   mc alias set local http://minio:9000 admin password123;

   mc mb local/tempo-data;

   exit 0;

   "




 tempo:

  image: grafana/tempo:latest

  container_name: tempo

  command:

  - -config.file=/etc/tempo.yaml

  volumes:

  - ./tempo.yaml:/etc/tempo.yaml

  ports:

  - "3200:3200"

  - "4317"

  depends_on:

  - createbucket




 alloy:

  image: grafana/alloy:latest

  container_name: alloy


  volumes:

  - ./config.alloy:/etc/alloy/config.alloy


  command:

  - run

  - /etc/alloy/config.alloy


  ports:

  - "4317:4317"

  - "4318:4318"




 frontend:

  image: python:3.11

  container_name: frontend

  volumes:

  - ./:/app

  working_dir: /app


  environment:

   OTEL_SERVICE_NAME: frontend

   OTEL_EXPORTER_OTLP_ENDPOINT: http://alloy:4317

   OTEL_EXPORTER_OTLP_INSECURE: "true"


  command: >

   sh -c "

   pip install -r requirements.txt &&
   opentelemetry-instrument python frontend.py

   "

  ports:

  - "5000:5000"





 cart:

  image: python:3.11

  container_name: cart

  volumes:

  - ./:/app

  working_dir: /app


  environment:

   OTEL_SERVICE_NAME: cart

   OTEL_EXPORTER_OTLP_ENDPOINT: http://alloy:4317

   OTEL_EXPORTER_OTLP_INSECURE: "true"


  command: >

   sh -c "

   pip install -r requirements.txt &&
   opentelemetry-instrument python cart.py

   "





 inventory:

  image: python:3.11

  container_name: inventory

  volumes:

  - ./:/app

  working_dir: /app


  environment:

   OTEL_SERVICE_NAME: inventory

   OTEL_EXPORTER_OTLP_ENDPOINT: http://alloy:4317

   OTEL_EXPORTER_OTLP_INSECURE: "true"


  command: >

   sh -c "

   pip install -r requirements.txt &&
   opentelemetry-instrument python inventory.py

   "




 payment:

  image: python:3.11

  container_name: payment

  volumes:

  - ./:/app

  working_dir: /app


  environment:

   OTEL_SERVICE_NAME: payment

   OTEL_EXPORTER_OTLP_ENDPOINT: http://alloy:4317

   OTEL_EXPORTER_OTLP_INSECURE: "true"


  command: >

   sh -c "

   pip install -r requirements.txt &&
   opentelemetry-instrument python payment.py

   "




 grafana:

  image: grafana/grafana

  container_name: grafana


  ports:

  - "3000:3000"


  volumes:

  - ./provisioning:/etc/grafana/provisioning


