version: "3"


services:


 flask:

  build: .

  ports:
   - "5000:5000"

  depends_on:
   - alloy




 alloy:

  image: grafana/alloy:latest


  volumes:

   - .alloy/config.alloy:/etc/alloy/config.alloy


  command:

   - run
   - /etc/alloy/config.alloy


  ports:

   - "4317:4317"

   - "4318:4318"




 mimir:

  image: grafana/mimir:latest


  command:

   - "-config.file=/etc/mimir.yml"


  volumes:

   - ./mimir.yml:/etc/mimir.yml


  ports:

   - "9009:9009"





 grafana:

  image: grafana/grafana


  ports:

   - "3000:3000"


  environment:

   GF_SECURITY_ADMIN_USER: admin

   GF_SECURITY_ADMIN_PASSWORD: admin



  volumes:


   # datasource automatic

   - ./datasource.yml:/etc/grafana/provisioning/datasources/datasource.yml


   # dashboard provider automatic

   - ./dashboard.yml:/etc/grafana/provisioning/dashboards/dashboard.yml


   # dashboard json automatic

   - ./flask-dashboard.json:/etc/grafana/provisioning/dashboards/flask-dashboard.json



  depends_on:

   - mimir
