version: "3"


services:


  flask:

    build: .

    container_name: flask-app

    ports:
      - "5000:5000"

    depends_on:
      - alloy




  alloy:

    image: grafana/alloy:latest

    container_name: alloy


    volumes:

      - ./config.alloy:/etc/alloy/config.alloy


    command:

      - run
      - /etc/alloy/config.alloy


    ports:

      - "4317:4317"

      - "4318:4318"


    depends_on:

      - mimir





  mimir:

    image: grafana/mimir:latest

    container_name: mimir


    command:

      - "-config.file=/etc/mimir.yml"


    volumes:

      - ./mimir.yml:/etc/mimir.yml


    ports:

      - "9009:9009"





  grafana:

    image: grafana/grafana:latest

    container_name: grafana


    ports:

      - "3000:3000"


    environment:

      GF_SECURITY_ADMIN_USER: admin

      GF_SECURITY_ADMIN_PASSWORD: admin


    volumes:


      # auto create Mimir datasource

      - ./datasource.yml:/etc/grafana/provisioning/datasources/datasource.yml


      # auto load dashboard provider

      - ./dashboard.yml:/etc/grafana/provisioning/dashboards/dashboard.yml


      # auto import dashboard

      - ./flask-dashboard.json:/etc/grafana/provisioning/dashboards/flask-dashboard.json



    depends_on:

      - mimir
