apiVersion: 1

datasources:

  # -------------------------
  # Tempo - Distributed Traces
  # -------------------------
  - name: Tempo
    type: tempo
    access: proxy
    uid: tempo
    url: http://tempo:3200
    isDefault: true

    jsonData:
      tracesToProfiles:
        datasourceUid: pyroscope
        tags:
          - service.name
          - env
        profileTypeId: process_cpu:cpu:nanoseconds


  # -------------------------
  # Pyroscope - Profiling
  # -------------------------
  - name: Pyroscope
    type: grafana-pyroscope-datasource
    access: proxy
    uid: pyroscope
    url: http://pyroscope:4040
