{
 "title": "Python Loki Observability",
 "panels": [
  {
   "title": "Application Logs",
   "type": "logs",
   "gridPos": { "x": 0, "y": 0, "w": 24, "h": 10 },
   "targets": [
    {
     "expr": "{service=\"payment-service\"}"
    }
   ]
  },
  {
   "title": "Only ERROR Logs",
   "type": "logs",
   "gridPos": { "x": 0, "y": 10, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "{level=\"ERROR\"}"
    }
   ]
  },
  {
   "title": "Error Count Last 5 Minutes",
   "type": "timeseries",
   "gridPos": { "x": 12, "y": 10, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "sum(count_over_time({level=\"ERROR\"}[5m]))"
    }
   ]
  },
  {
   "title": "Total Log Volume",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 18, "w": 24, "h": 8 },
   "targets": [
    {
     "expr": "sum(rate({service=\"payment-service\"}[1m]))"
    }
   ]
  }
 ]
}